apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: acc-tests-pipeline
spec:
  resources:
  - name: acc-test-repo
    type: git
    
  tasks:
  - name: run-go-tests
    taskRef:
      name: run-all-acc-tests
      kind: ClusterTask
    resources:
      inputs:
      - name: acc-test-repo
        resource: acc-test-repo
